name: Module 1 homework

on: [push, pull_request]
jobs:
  fibonacci:
    runs-on: ubuntu-latest
    strategy:    
      matrix:
        cc: [gcc, clang]
        optimize: [0, 1, 2, 3, fast, s]
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Create build directory
      run: mkdir module1/homework/fibonacci/build
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.cc }}
    - name: Compile
      env:
        CC: ${{ matrix.cc }}
      working-directory: module1/homework/fibonacci/build
      run: |
        echo "C++ Compiler:"
        ${CC} --version
        cmake -DCMAKE_CXX_FLAGS=-O${{matrix.optimize}} ..
        make
    - name: Run tests
      working-directory: module1/homework/fibonacci/build
      run: ctest -V
